before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
    - "metafates/mangal:latest"
    skip_push: false
    use: docker

brews:
  -
    name: mangal

    tap:
      owner: metafates
      name: homebrew-mangal
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/metafates/mangal"
    description: "The ultimate CLI manga downloader!"
    license: "MIT"
    skip_upload: false

    test: |
      system "#{bin}/mangal -v"

    install: |-
      bin.install "mangal"
      bash_completion.install "completions/mangal.bash" => "mangal"
      zsh_completion.install "completions/mangal.zsh" => "_mangal"
      fish_completion.install "completions/mangal.fish"

scoop:
  bucket:
    owner: metafates
    name: scoop-metafates
    branch: main
    token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"

  folder: bucket

  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com

  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/metafates/mangal"
  description: "The ultimate CLI manga downloader!"
  license: MIT
  skip_upload: false


release:
  github:
    owner: metafates
    name: mangal

  draft: false
  name_template: "{{.ProjectName}} v{{.Version}}"

nfpms:
  -
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/metafates/mangal
    maintainer: metafates <fates@duck.com>
    description: |-
      The most advanced cli manga downloader in the entire universe!

    license: MIT
    formats:
      - deb
      - rpm

    bindir: /usr/bin
    section: utils

    contents:
      - src: ./completions/mangal.bash
        dst: /usr/share/bash-completion/completions/mangal
        file_info:
          mode: 0644
      - src: ./completions/mangal.fish
        dst: /usr/share/fish/completions/mangal.fish
        file_info:
          mode: 0644
      - src: ./completions/mangal.zsh
        dst:  /usr/share/zsh/vendor-completions/_mangal
        file_info:
          mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
